name: "SQL Formatter"

author: "ryohidaka"

description: "GitHub Actions to formats SQL using sql-formatter."

branding:
  color: green
  icon: send

inputs:

runs:
  using: "composite"
  steps:
    - name: Set GitHub Path
      run: echo "GITHUB_ACTION_PATH=${GITHUB_ACTION_PATH}" >> $GITHUB_ENV
      shell: bash

    - name: Setup Node.js
      uses: actions/setup-node@v4
