name: "SQL Formatter"

author: "ryohidaka"

description: "GitHub Actions to formats SQL using sql-formatter."

branding:
  color: yellow
  icon: check-circle

inputs:
  path:
    description: "Directory path to format SQL files."
    required: false
    default: "."

  config:
    description: "Additional path to config JSON file or json string for sql-formatter (e.g. language, tab-width, etc.)"
    required: false
    default: ""

  # commit options
  commit-user-name:
    required: false
    default: "GitHub Actions"
    description: "Commit username. Defaults to 'GitHub Actions'."

  commit-user-email:
    required: false
    default: "actions@github.com"
    description: "Commit email. Defaults to 'actions@github.com'."

  commit-message:
    required: false
    default: "chore: Format SQL files"
    description: "Commit message. Defaults to 'chore: Format SQL files'."

  dry-run:
    description: "If true, the commit and push steps will be skipped."
    required: false
    default: "false"

runs:
  using: "composite"
  steps:
    - name: Set GitHub Path
      run: echo "GITHUB_ACTION_PATH=${GITHUB_ACTION_PATH}" >> $GITHUB_ENV
      shell: bash

    - name: Setup Node.js
      uses: actions/setup-node@v4

    - name: Install sql-formatter
      run: npm install -g sql-formatter
      shell: bash

    - name: Format SQL files
      run: |
        $GITHUB_ACTION_PATH/scripts/format.sh \
          "${{ inputs.path }}" \
          "${{ inputs.config }}"
      shell: bash

    - name: Commit and Push
      uses: ryohidaka/action-commit-push@v0.3.0
      with:
        files: "${{ inputs.path }}"
        commit-user-name: "${{ inputs.commit-user-name }}"
        commit-user-email: "${{ inputs.commit-user-email }}"
        commit-message: "${{ inputs.commit-message }}"
        dry-run: ${{ inputs.dry-run }}
