name: "SQL Formatter"

author: "ryohidaka"

description: "GitHub Actions to formats SQL using sql-formatter."

branding:
  color: green
  icon: send

inputs:
  path:
    description: "Directory path to format SQL files."
    required: false
    default: "."

runs:
  using: "composite"
  steps:
    - name: Set GitHub Path
      run: echo "GITHUB_ACTION_PATH=${GITHUB_ACTION_PATH}" >> $GITHUB_ENV
      shell: bash

    - name: Setup Node.js
      uses: actions/setup-node@v4

    - name: Install sql-formatter
      run: npm install -g sql-formatter
      shell: bash

    - name: Format SQL files
      run: |
        $GITHUB_ACTION_PATH/scripts/format.sh "${{ inputs.path }}"
      shell: bash
